# docker-compose.yml
version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: social-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - social-app-network

  backend:
    build: ./backend
    container_name: social-backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - PORT=5000
      - CORS_ORIGIN=http://localhost:8080 # Port of the frontend service
      - MONGO_URI=mongodb://mongo:27017/social_dashboard
      - JWT_SECRET=your_docker_secret_key
      - STORAGE_PROVIDER=cloudinary
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    networks:
      - social-app-network

  frontend:
    build: ./frontend
    container_name: social-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - social-app-network

networks:
  social-app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
